# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCMU8182EklmPpcXvdS5erULvdkjjGBE
"""

import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-2 * np.pi, 2 * np.pi, 500)
y = np.sin(x)


plt.figure(figsize=(8, 6))
plt.plot(x, y, label='y = sin(x)', color='blue', linewidth=2)
plt.title("y = sin(x) Grafigi", fontsize=14)
plt.xlabel("x", fontsize=12)
plt.ylabel("y", fontsize=12)
plt.axhline(0, color='black', linewidth=0.5, linestyle='--')
plt.axvline(0, color='black', linewidth=0.5, linestyle='--')
plt.grid(color='gray', linestyle='--', linewidth=0.5)
plt.legend(fontsize=12)
plt.show()

import numpy as np
import matplotlib.pyplot as plt


num_points = 100
x = np.random.rand(num_points) * 10
y = np.random.rand(num_points) * 10


plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='purple', alpha=0.7, edgecolors='black')
plt.title("Tasodifiy Nuqtalar Grafiki", fontsize=14)
plt.xlabel("X koordinatalari", fontsize=12)
plt.ylabel("Y koordinatalari", fontsize=12)
plt.grid(color='gray', linestyle='--', linewidth=0.5)
plt.show()

from PIL import Image

def convert_to_black_and_white(input_path, output_path):
    img = Image.open(input_path)
    bw_img = img.convert("L")
    bw_img.save(output_path)
    print(f"Oq-qora rasm saqlandi: {output_path}")

input_file = "photo_2024-11-30_15-27-05.jpg"
output_file = "output_bw.jpg"
convert_to_black_and_white(input_file, output_file)